In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [105]:
## your code
def func1(x):
    return (2**x)/x
a = np.arange(1,21)
print(func1(a))

[  2.00000000e+00   2.00000000e+00   2.66666667e+00   4.00000000e+00
   6.40000000e+00   1.06666667e+01   1.82857143e+01   3.20000000e+01
   5.68888889e+01   1.02400000e+02   1.86181818e+02   3.41333333e+02
   6.30153846e+02   1.17028571e+03   2.18453333e+03   4.09600000e+03
   7.71011765e+03   1.45635556e+04   2.75941053e+04   5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [107]:
## your code
def func2(x):
    return 0.1**(3*x)
def func3(x):
    return 0.2**(4*x)
a = np.arange(0,6)
x = func2(a)
y = func3(a)
print((x*y).sum())


1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [30]:
## your code
a3 = np.zeros((8,8))
a3[0:8:2,0:8:2] = 1
a3[1:8:2,1:8:2] = 1
print(a3)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [59]:
X = np.random.random((5, 2))
Y = np.zeros((5,2))
Y[:,0] = np.sqrt( X[:,0]**2 + X[:,1]**2)
Y[:,1] = np.arctan(X[:,1]/X[:,0])
print(Y)

## your code

[[ 0.77926198  1.25108833]
 [ 0.72606549  1.25491639]
 [ 0.71634964  1.54074209]
 [ 1.07643419  0.95180427]
 [ 0.22592505  1.12314727]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [103]:
X = np.random.random((10, 10))
print(np.argmax(X))
print("[",np.argmax(X)//10,",",np.argmax(X)%10,"]")
print(X.reshape((100))[np.argmax(X)])
print(X[np.argmax(X)//10,np.argmax(X)%10])
## your code

91
[ 9 , 1 ]
0.992161769615
0.992161769615


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [73]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
r = X - y
d = np.sqrt( r[:,0]**2 + r[:,1]**2)
print(d[np.argmin(d)])
print(d)

## your code

0.0405269674008
[ 0.90090337  0.54275211  0.77056128  0.56757014  0.04052697  0.30011381
  0.62952583  0.12202035  0.12378448  0.11199478]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [51]:
## your code
@np.vectorize
def func(x):
    if x < 0:
        return (x**2 + 2*x + 6)
    elif x <= 2:
        return (x + 6)
    else:
        return (x**2 + 4*x -4)
print(func(np.arange(-3,3.1,0.1)))
   

[  9.     8.61   8.24   7.89   7.56   7.25   6.96   6.69   6.44   6.21   6.
   5.81   5.64   5.49   5.36   5.25   5.16   5.09   5.04   5.01   5.     5.01
   5.04   5.09   5.16   5.25   5.36   5.49   5.64   5.81   6.     6.1    6.2
   6.3    6.4    6.5    6.6    6.7    6.8    6.9    7.     7.1    7.2    7.3
   7.4    7.5    7.6    7.7    7.8    7.9    8.     8.81   9.64  10.49
  11.36  12.25  13.16  14.09  15.04  16.01  17.  ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [63]:
X = np.random.random((10, 10))
u = np.mean(X,axis = 1)
Y = X.T - u;
Y = Y.T
print(np.mean(Y,axis=1))
#print(u)
#print(X)
#print(Y)
## your code

[  5.55111512e-17   0.00000000e+00  -3.33066907e-17   4.44089210e-17
  -5.55111512e-17   0.00000000e+00  -4.44089210e-17   7.77156117e-17
  -3.33066907e-17  -2.22044605e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [43]:
X = np.random.normal(loc=5, scale=2., size=1000)

print(X.sum()/1000)
print(((X.sum()/1000 - X)**2).sum()/1000 )


4.91346293638
3.99372124222


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
## your code
a = np.ones((5,5))
b = np.arange(0,5)
a = a*b
a = a.T + b
a = a%5
a


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.,  0.],
       [ 2.,  3.,  4.,  0.,  1.],
       [ 3.,  4.,  0.,  1.,  2.],
       [ 4.,  0.,  1.,  2.,  3.]])